export const SET_BOOKS = "SET_BOOKS";
export const SEARCH_BOOKS = "SEARCH_BOOKS";
export const SET_BOOK_DETAILS = "SET_BOOK_DETAILS";
export const CREATE_BOOK = "CREATE_BOOK";
export const UPDATE_BOOK = "UPDATE_BOOK";
export const DELETE_BOOK = "DELETE_BOOK";
export const TOGGLE_FAVORITE = "TOGGLE_FAVORITE";
export const VIEW_FAVORITES = "VIEW_FAVORITES";
